spring:  
application:  
  name:springboot-hiworld
server:
    port:8087
    
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springjdbcdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: SPRINGBOOT-JDBC-APP